#
# Component Makefile

COMPONENT_ADD_INCLUDEDIRS := .

CFLAGS += -D__EVENTGROUP=$(CONFIG_EVENTGROUP_NAME) 
CFLAGS += -D__NTP_SYNCED=$(CONFIG_NTP_SYNCED) 
CFLAGS += -D__WIFI_CONNECTED=$(CONFIG_WIFI_CONNECTED) 
CFLAGS += -D__MSG_QUEUED_VALUE=$(CONFIG_MSG_QUEUED_VALUE) 
